language: cpp
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          update: true
          packages:
            - libtool-bin

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          update: true
          packages:
            - libtool-bin
    
    - os: osx

script: 
    - cd  ${TRAVIS_BUILD_DIR}/test
    - rm ./tls/dh1024.pem
    - openssl dhparam -out ./tls/dh1024.pem 1024
    - cat package.json
    - npm install
    - npm test
    - cat /tmp/drachtio.log

git:
    submodules: false

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get install curl libz-dev ncurses-dev libpcap-dev libtool
    - sudo chmod 0777 /usr/local/src 
    - cd /usr/local/src
    - git clone https://github.com/SIPp/sipp.git && cd sipp && git checkout v3.5.1 
    - ./build.sh  --with-rtpstream --with-pcap 
    - sudo make install
    - sudo apt-get install -y libcurl4-openssl-dev
    - sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
    - sudo apt-get install -y nodejs
    - curl-config --version
    - curl-config --libs 
    - cd $TRAVIS_BUILD_DIR
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - ./autogen.sh
    - mkdir build && cd build
    - ../configure
    - make
    - ./drachtio --version 
    - node --version
    - npm --version
